# Generated by Django 4.0.5 on 2022-06-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='desc',
            new_name='dest',
        ),
    ]
