# Generated by Django 4.0.5 on 2022-06-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0002_rename_desc_destination_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
