# Generated by Django 4.0.5 on 2022-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0003_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(height_field=20, upload_to='images/', width_field=20)),
                ('audio', models.FileField(upload_to='media')),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
